services:
  app:
    build:
      context: .
      args:
        # Loads args from the .env file.
        BUILD_IMAGE: ${BUILD_IMAGE:-eclipse-temurin:24_36-jdk-alpine-3.21}
        IMAGE: ${IMAGE:-eclipse-temurin:24_36-jre-alpine-3.21}
    ports:
      - "8085:8085"
    env_file:
      - .env
