POST localhost:8085/generate/sikkerhetsmetrikker
Content-Type: application/json

{
  "initialRiSc": "{\"schemaVersion\":\"4.0\",\"title\":\"ss\",\"scope\":\"ss\",\"valuations\":[],\"scenarios\":[]}"
}